### ISSUE TITLE
200 parcel Schaefer atlas

### ISSUE THREAD

**Issue by SimonaPWH** [ggsegverse/ggsegSchaefer#3]
Dear Dr. Mowinckel,

I LOVE your package and would really like to make use of it more often. However, almost all atlas-based projects in my lab use the 200 parcel not the 400 parcel Schaefer atlas - are there any plans to include the 200 parcel one in the ggsegExtra repo? 

-Simona

**Comment by drmowinckels** [comment]
Hi. Thanks for a bump on this issue. 

We have a PR ongoing with more parcellations for this atlas. Note that these are not 100% debugged yet, but seems to be mainly in order. You can read about the ongoing conversation about this PR in #2 .

To install and test this PR, you can install directly from the contributors repository to test it out.

```r
remotes::install_github("monicathieu/ggsegSchaefer")
```

**Comment by zhenglukai** [comment]
> Hi. Thanks for a bump on this issue.
> 
> We have a PR ongoing with more parcellations for this atlas. Note that these are not 100% debugged yet, but seems to be mainly in order. You can read about the ongoing conversation about this PR in #2 .
> 
> To install and test this PR, you can install directly from the contributors repository to test it out.
> 
> ```r
> remotes::install_github("monicathieu/ggsegSchaefer")
> ```

Thank you! This is really helpful. It would be great if these additional atlas can be merged into the main build of ggsegSchaefer.

**Comment by drmowinckels** [comment]
Hi! The atlases are now merged into the main build, and I hope they work out for you :)
