### ISSUE TITLE
Schaefer atlas release version

### ISSUE THREAD

**Issue by cookpa** [ggsegverse/ggsegSchaefer#6]
Hi,

Thanks for sharing this amazing resource!

What version of the Schaefer atlas was used in this package? It would be great if this was available in the code, so that user scripts could check for compatibility with analyzed data.

**Comment by drmowinckels** [comment]
This is a very reasonable request!

@monicathieu do you remember which version you used for the updated annotations?

**Comment by monicathieu** [comment]
Great question! I'm currently away from the machine where I'd be able to double-check the parcellation version number, but I'm 95% sure it should be 0.17.0. (I can update next week once I can get back into that machine) There's a small chance it's 0.17.1, but that version difference shouldn't affect parcel labeling as the cifti files updated in parcellation 0.17.1 aren't used to create ggseg's parcel snapshots.

**Comment by drmowinckels** [comment]
great that you are looking into it. Just let me know what you figure out when you do, and I'll update the documentation. :)

**Comment by monicathieu** [comment]
For whatever reason I never posted back here! ack! but I can confirm that the Schaefer atlas used was version **0.17.1**.

**Comment by drmowinckels** [comment]
Thanks for coming back with this, @monicathieu ! 
I've now added this information various spots in the docs in 483cd726afded2b4d63063cf696b6fc56ff549b1 :)
