### ISSUE TITLE
Several parcels missing in 200-parcel 7-network atlas

### ISSUE THREAD

**Issue by mcfreund** [ggsegverse/ggsegSchaefer#7]
Hi,

Thank you for this wonderful package. Several right medial parcels appear to be missing in the 200-parcel 7-network version.

```r
library(ggseg)
library(ggseg3d)
library(ggsegExtra)
library(ggsegSchaefer)
library(ggplot2)
ggplot() +
  geom_brain(atlas = schaefer7_200, position = position_brain(hemi ~ side)) +
  guides(fill = "none")
sessionInfo()
```

![image](https://user-images.githubusercontent.com/22828878/147690562-e7889647-e305-4d21-85fa-481ca9b7f054.png)

> R version 4.0.3 (2020-10-10)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 10 x64 (build 19043)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
> [4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] ggplot2_3.3.5         ggsegSchaefer_2.0.3   ggsegExtra_1.5.33.004 ggseg3d_1.6.3         ggseg_1.6.4          
> 
> loaded via a namespace (and not attached):
>  [1] httr_1.4.2         tidyr_1.1.4        jsonlite_1.7.2     viridisLite_0.3.0  splines_4.0.3      R.utils_2.10.1    
>  [7] freesurfer_1.6.8   assertthat_0.2.1   sp_1.4-5           pillar_1.6.2       lattice_0.20-41    glue_1.4.2        
> [13] digest_0.6.27      geomorph_4.0.1     colorspace_2.0-0   htmltools_0.5.1.1  Matrix_1.2-18      R.oo_1.24.0       
> [19] plyr_1.8.6         pkgconfig_2.0.3    raster_3.5-9       stars_0.5-5        magick_2.6.0       RNifti_1.3.0      
> [25] purrr_0.3.4        scales_1.1.1       terra_1.4-22       jpeg_0.1-8.1       tibble_3.0.6       proxy_0.4-26      
> [31] farver_2.0.3       generics_0.1.0     ellipsis_0.3.2     withr_2.4.1        lazyeval_0.2.2     oro.nifti_0.11.0  
> [37] RRPP_1.1.2         magrittr_2.0.1     crayon_1.4.1       R.methodsS3_1.8.1  fansi_0.4.2        nlme_3.1-149      
> [43] lwgeom_0.2-8       class_7.3-17       tools_4.0.3        data.table_1.13.6  hms_1.0.0          lifecycle_1.0.1   
> [49] matrixStats_0.58.0 stringr_1.4.0      plotly_4.10.0      munsell_0.5.0      compiler_4.0.3     e1071_1.7-9       
> [55] pbmcapply_1.5.0    rlang_0.4.10       classInt_0.4-3     units_0.7-2        grid_4.0.3         rstudioapi_0.13   
> [61] htmlwidgets_1.5.3  bitops_1.0-6       gtable_0.3.0       codetools_0.2-16   abind_1.4-5        DBI_1.1.1         
> [67] neurobase_1.32.1   reshape2_1.4.4     R6_2.5.0           knitr_1.36         dplyr_1.0.4        rgdal_1.5-28      
> [73] smoothr_0.2.2      utf8_1.1.4         KernSmooth_2.23-17 readr_1.4.0        ape_5.6            stringi_1.5.3     
> [79] parallel_4.0.3     Rcpp_1.0.7         vctrs_0.3.8        sf_1.0-3           rgl_0.107.14       tidyselect_1.1.0  
> [85] xfun_0.23

**Comment by drmowinckels** [comment]
Thanks for the bug report! The fixed version can be installed from GiHub, and will be available from the ggseg r-universe within a couple of hours.
