### ISSUE TITLE
Wrong URL in the About section

### ISSUE THREAD

**Issue by SamGuay** [ggsegverse/ggsegSchaefer#8]
Hello there,
It appears the repo was moved from https://github.com/LCBC-UiO/ggsegSchaefer/ to the ggseg org but the URL in the About section wasn't updated and the automated redirection doesn't work.

Here's a picture of the About section atm:
![image](https://user-images.githubusercontent.com/30598330/150857336-c3d545bd-2bb5-4189-bb67-9d026c20e0d7.png)

I guess the official doc for this package is https://ggseg.github.io/ggsegSchaefer/ from now on?

Note that redirections from the package doc (ie, Browse source code at https://​github.com/​LCBC-UiO/​ggsegSchaefer/​ and     Report a bug at https://​github.com/​LCBC-UiO/​ggsegSchaefer/​issues) do work.

Thanks

**Comment by drmowinckels** [comment]
thanks for the notice! We've altered the url. Redirects on github are really good when it comes to repository owner changes, but the documentation pages dont have this redirect.
